konstagramproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainApp.urls')),
    path('login/', include('loginSigninApp.urls')), # Appname
    path('board/', include('boardApp.urls')), # Appname
] 

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

loginSigninApp/urls.py
from django.urls import path,include
from .views import *

app_name = 'loginSigninApp'

urlpatterns = [

    path('', login, name='login'),    # /login/
    path('signup/',signup, name='signup'), # /login/signup/
    
]

mainApp/urls.py
from django.urls import path
from .views import *
app_name = 'mainApp'

urlpatterns = [
    path('',mainpage,name='mainPage'),
    path('create-post/',create_post,name="create-post")
]

loginSigninApp/models.py
from django.db import models
from mainApp.models import *
# Create your models here.

loginSigninApp/views.py
from django.shortcuts import render
from mainApp.models import *
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
import json
import hashlib
import hmac
import base64
import requests
import time,json
import string,random
# Create your views here.


def login(request):
    return render(request, 'signin.html', {})

@csrf_exempt
def signup(request):
    if request.method == "GET":
        return render(request, 'signup.html')

    elif request.method == "POST":
        if(request.POST['type'] == 'certification'):
            randomNum = makeRandomNum(8)
            sendMessage(request.POST['username'],request.POST['phone_number'],randomNum)
            context = {'state':'complete','randomNum':randomNum}
            return JsonResponse(json.dumps(context),safe=False)
        elif(request.POST['type'] == 'input_user'):            
            username = request.POST['username']
            password = request.POST['password']    
            user_id = request.POST['user_id']      
            student_id = request.POST['student_id']
            user_major = request.POST['user_major']
            user_email = request.POST['user_email']
            res_data = {}
            if not(username and password and user_id and student_id and user_major and user_email):
                res_data['error'] = '모든 값을 입력해야 합니다.'   
                print("모든값입력 필요")
        # Input userdata to models
            else:
                user = us_info(name = username,
                            password= password,
                            student_id = student_id,
                            major = user_major,
                            user_email = user_email,
                            account_id = user_id)
                user.save()
                print("세이브완료")
            return render(request, 'signup.html', res_data)
                    

def makeRandomNum(length):
    _Length = length
    string_pool = string.digits
    result = ""
    for i in range(_Length):
        result += random.choice(string_pool)
    return result


def sendMessage(name,phoneNumber,randomNumber):
    print(name + "," + phoneNumber)
    timestamp = int(time.time() * 1000)
    timestamp = str(timestamp)
    url = "https://sens.apigw.ntruss.com"
    requestUrl = "/sms/v2/services/"
    requestUrl2 = "/messages"
    serviceId = "ncp:sms:kr:263907291783:checking_identification"
    access_key = "F4OkzLuEx7hsYwvITZph"

    uri = requestUrl + serviceId + requestUrl2
    apiUrl = url + uri


    def make_signature(uri,access_key):
        secret_key = "fkLllWfvlPdE06CLjSpOBu8Q5xdBC98ViZaUJGq9"
        secret_key = bytes(secret_key,'UTF-8')
        method = "POST"
        message = method + " " + uri + "\n" + timestamp + "\n" + access_key
        message = bytes(message,"UTF-8")
        signingKey = base64.b64encode(hmac.new(secret_key,message,digestmod=hashlib.sha256).digest()) 
        return signingKey


    message = {"to":phoneNumber}

    body = {
        "type":"SMS",
        "contentType":"COMM",
        "from":"01091447156",
        "subject":name+"님",
        "content" : "다음의 숫자를 입력해주세요\n"+randomNumber,
        "messages":[message]
    }

    body2 = json.dumps(body)
    headers = {
        'Content-Type':'application/json; charset=utf-8',
        'X-ncp-apigw-timestamp':timestamp,
        'x-ncp-iam-access-key':access_key,
        'x-ncp-apigw-signature-v2':make_signature(uri,access_key)
    }

    res = requests.post(apiUrl,headers=headers,data=body2)

    res.request
    res.status_code
    res.raise_for_status()

    return res.json()
             
                        

loginSigninApp/templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0, minimum-scale=1.0">
    <title>로그인</title>

    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />

</head>

<body>
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="signin.html">
                        <div class="logo_text">Together</div>
                    </a>
                    <div class="explain_text">함께하는 즐거움을 느껴봐요!</div>
                </h1>
            </section>
        </header>

        <div class="details" id="input_box">
            <div class="input_box" id="input_box">
                <div class="input_box_detail">
                    <form>
                        <input type="text" placeholder="아이디를 입력하세요." id="userid" name="user_id">
                        <div class="password-box">
                            <input type="password" placeholder="비밀번호를 입력하세요." id="userpw" name="user_pw">
                            <i class="far fa-eye-slash" id="showIcon"></i>
                        </div>
                        <input type="submit" value="로그인" id="signin_btn" onclick="">
                    </form>
                </div>
                <div class="login_details">
                    <hr class="line" size="1" color="#bbbbbb">

                    <div class="find">
                        <a id="find_idpw">아이디/비밀번호 찾기</a>
                    </div>

                    <div class="signUp">
                        <span>계정이 아직 없으신가요? </span>
                        <a href="{% url 'loginSigninApp:signup' %}">회원가입</a>
                    </div>
                </div>
            </div>

        </div>

         <!-- 아이디 찾기 -->
         <form class="input_box1" id="input2">
            <div class="find_box">
                <a id="find_id" >아이디 찾기</a>
                <a id="find_pw" >비밀번호 찾기</a>
            </div>
            <input type="text" placeholder="이름을 입력하세요." class="username">
            <input type="text" placeholder="가입한 이메일을 입력하세요." class="useremail">
            <input type="submit" value="아이디 찾기" id="idfind_btn" onclick="">
        </form>

        <!-- 비밀번호 찾기 -->
        <form class="input_box1" id="input3">
            <div class="find_box">
                <a id="find_id_on" >아이디 찾기</a>
                <a id="find_pw_on" >비밀번호 찾기</a>
            </div>
            <input type="text" placeholder="가입한 아이디를 입력하세요." id="signedupId">
            
            <input type="text" placeholder="가입한 이메일을 입력하세요." class="useremail">
            <input type="submit" value="비밀번호 찾기" id="pwfind_btn" onclick="">
        </form>


    </section>

    <script src="{% static 'js/signin.js' %}"></script>
</body>

</html>

loginSigninApp/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0, minimum-scale=1.0">
    <title>회원가입</title>

    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>

</head>
<body>
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="signup.html">
                        <div class="logo_text">Together</div>
                    </a>
                    <div class="explain_text">본인인증</div>
                </h1>
            </section>
        </header>

        <!-- 본인인증 폼 -->
        <div class="input_box" id="cfForm">
            <input type="text" placeholder="이름을 입력하세요." class="username">
            <input type="text" placeholder="전화번호를 입력하세요." id="userphone">
            <input type="submit" value="본인 인증하기" id="certification" >
            <input type="text" id="hidden_type" value="certification" style="display: none;">
            <div id="cf_box">
                <input type="text" placeholder="인증번호를 입력하세요." id="cf_num">
                <div class="timer">3:00</div>
                <a id="cf_btn">인증</a>
            </div>
            <div id="next">다음</div>
        </div>

        <!-- 회원가입 폼 -->
        <form class="input_box" id="signupForm" method="POST" action="">
            {% csrf_token %}
            <input type="text" placeholder="이름을 입력하세요." class="username" name="username">
            <select id="usernum" name="student_id">
                <option value="none" hidden >학번을 선택하세요.</option>
                <option value="21">21학번</option>
                <option value="20">20학번</option>
                <option value="19">19학번</option>
                <option value="18">18학번</option>
                <option value="17">17학번</option>
                <option value="16">16학번</option>
                <option value="15">15학번</option>
            </select>
            <i class="fas fa-sort-down" id="select_num"></i>
            <select id="userdept" name="user_major">
                <option value="none" hidden>학과를 선택하세요.</option>
                <option value="의료IT공학과">의료IT공학과</option>
                <option value="의공학과">의공학과</option>
                <option value="의료공긴디자인학과">의료공간디자인학과</option>
                <option value="제약생명공학과">제약생명공학과</option>
                <option value="의료인공지능학과">의료인공지능학과</option>
                <option value="의료신소재학과">의료신소재학과</option>
            </select>
            <i class="fas fa-sort-down" id="select_dept"></i>
            <input type="text" placeholder="이메일을 입력하세요." id="useremail" name="user_email">
            <input type="text" placeholder="아이디를 입력하세요." id="userid" name="user_id">
            <input type="password" placeholder="비밀번호를 입력하세요." id="userpw" name="password">
            <input type="submit" value="회원가입" id="signup_btn" onclick="location.href = './signin.html'">
        </form>
    </section>

    <script src="{% static 'js/signup.js' %}"></script>
</body>
</html>