boardApp/urls.py
from django.urls import path
from .views import *
app_name = 'boardApp'

urlpatterns = [
    path('',boardPage,name='boardPage'),
    path('question-and-answer/',Question_and_answer,name='question-and-answer'),
]

konstagramproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainApp.urls')),
    path('login/', include('loginSigninApp.urls')), # Appname
    path('board/', include('boardApp.urls')), # Appname
] 

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

loginSigninApp/urls.py
from django.urls import path,include
from .views import *

app_name = 'loginSigninApp'

urlpatterns = [

    path('', login, name='login'),    # /login/
    path('signup/',signup, name='signup'), # /login/signup/
    
]

mainApp/urls.py
from django.urls import path
from .views import *
app_name = 'mainApp'

urlpatterns = [
    path('',mainpage,name='mainPage'),
    path('create-post/',create_post,name="create-post")
]

boardApp/views.py
from typing import DefaultDict
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from mainApp.models import *
from django.views.decorators.csrf import csrf_exempt
import json
# Create your views here.
@csrf_exempt
def boardPage(request):


    if request.method == "POST":

        if(request.POST.get('type') == "addPost"):
            return JsonResponse({"state":'addPost',"board_title":request.POST.get('board_title')})
        elif request.POST.get('type') == "deleteBoard":
            print(request.POST.get('board_title'))
            board_nm = request.POST.get('board_title')
            bulletin_board = Bulletin_board.objects.filter(board_name = board_nm).delete()
            print(bulletin_board)
            return JsonResponse({"state":'deleteBoard'})
        elif request.POST.get('type') == "createBoard":
            board_form = Bulletin_board(board_name = request.POST.get('board_name'),bulletin_board_instruction = request.POST.get('board_content'),profile_id= Profile.objects.filter(account_id="shinjuno123")[0])
            board_form.save()
            return JsonResponse({"state":'createBoard'})
        elif request.POST.get('type') == "enterIntoBoard":
            board = Bulletin_board.objects.get(board_name = str(request.POST.get('board_name')))
            posts = Post.objects.filter(bulletin_board_name = board).order_by('-modified_at')[:3]

            images = []

            for post in posts:
                image = Post_Image_Url.objects.filter(post_id=post)
                if len(image) is not 0:
                    images.append(queryset_to_json(image))



            return JsonResponse({"state":'enterIntoBoard',"posts":queryset_to_json(posts),"images":images})
    else : 
        boards = Bulletin_board.objects.all();
        images = Post_Image_Url.objects.all()


        post_contexts= DefaultDict(list)
        board_context = DefaultDict(list)

        count = 1
        for board in boards:
            post = Post.objects.filter(bulletin_board_name=board).values().order_by('-modified_at')[:15]
            board_context[str(count)].append(board)
            post_contexts[str(count)].append(post)
            count += 1

        tmpcontext = {}
    
        for index in post_contexts:
            tmpcontext['board' + str(index)] = get_post_length_at_index(post_contexts,index)
        context = {'post_contexts_for_each_boards':tmpcontext,'board_contexts':board_context,'images':images}

        return render(request,'boardpage.html',context=context)


def Question_and_answer(request):
    return render(request,'question.html')

def get_post_length_at_index(object_list,index):
    return object_list[index][0]


def queryset_to_json(objects):
    arr = []
    for object in objects.values():
        arr.append(object)
    return arr

boardApp/templates/boardpage.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/mainpage.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/boardpage.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/bc1f5db172.js" crossorigin="anonymous"></script>
    <title>Konstargram</title>
</head>

<body>
    <header>
        <div class="header-left">
            <a href="{% url 'mainApp:mainPage' %}"><img src="" alt="">로고</a>
            <i class="fas fa-chevron-right"></i>
            <a href="{% url 'boardApp:boardPage' %}">전체 게시판</a>
            <i class="fas fa-chevron-right" id="logo-board-icon"></i>
            <p id="logo-board"></p>
        </div>
        <div class="header-right">
            <div class="realtimeSearch">
                <span class="realtimeSearch-span">
                    실시간 인기 검색어
                    <i class="fas fa-caret-down"></i>
                </span>
                <div class="realtimeSearch-dropdown">
                    <a href="#" id="s1">삼색이</a>
                    <a href="#" id="s2">야통이</a>
                    <a href="#" id="s3">무</a>
                </div>
            </div>
            <input type="text" placeholder="검색" id="search">
            <a href="{% url 'loginSigninApp:login' %}" id="login">로그인</a>
            <i class="fas fa-user"></i>
            <i class="fas fa-bars" id="rightMenu"></i>
        </div>
    </header>

    <section class="chart">
        <!-- Center Chart -->
        <ul class="centerChart">
            {% for post_contexts in post_contexts_for_each_boards %}
            <div class="postList">
          
                <div class="board-title">
                    <div class="board-click">
                        <p class="postTitle">{% get_title_at_index board_contexts forloop.counter %}</p>
                        <p class="postExplain">{% get_content_at_index board_contexts forloop.counter %}</p>
                    </div>
                    <div class="postMenu">
                        <p class="postCount">posts 1,234</p>
                        <i class="fas fa-ellipsis-h" id="editboardIcon"></i>
                    </div>
                </div>

                <ul class="postChart" id="scroll">
                    {% get_post_by_index post_contexts_for_each_boards post_contexts as posts%}
                    {% for post in posts %}
                    <li>
                        <div>
                            <div class="post-click">
                                {% get_image images post.id as image%}
                                {% if image != None %}
                                <img class="post1" src="/media/{% get_image images post.id %}"
                                    alt="/media/{% get_image images post.id %}">
                                {% else %}
                                <p class="postContent" id="postContent">{{post.post_contents}}</p>
                                {% endif %}
                                <p class="postExplain" id="postExplain">{{post.post_title}}</p>
                                <div class="postHover">
                                    <div class="post-top">
                                        <p class="postComment">{{post.profile_id}}</p>
                                    </div>
                                    <div class="post-bottom">
                                        <i class="fas fa-heart"> 1,234</i>
                                        <p class="postComment">댓글56</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}

                </ul>
                <div class="editBoard">
                    <p class="addPost">게시물 추가</p>
                    <p class="deleteBoard">게시판 삭제</p>
                </div>
            </div>
            {% endfor %}
            <script>
                const create_page_URL = "{% url 'mainApp:create-post' %}"
            </script>
        </ul>

        
        <div class="newBoard">새 게시판 만들기</div>

        <div id="modal">
            <form class="newBoard-modal">
                <div>
                    <h2>새 게시판 생성</h2>
                    <p id="modal_close_btn">X</p>
                </div>
                <input type="text" placeholder="게시판 제목" id="newBoard-title" value="">
                <input type="text" placeholder="한 줄 설명을 적어주세요." id="newBoard-explain" value="">
                <input type="button" value="생성" id="add_btn" onclick="createBoardButton()">
            </form>
            <div class="modal_layer"></div>
        </div>



        <!-- 게시판 안의 게시물들 -->
        <ul class="centerChart" id="posts">
         
        </ul>



        <!-- Right Chart -->
        <ul class="rightChart">
            <ul class="noticeBoard">
                <a href="{% url 'boardApp:boardPage' %}"><i class="fas fa-clipboard"></i>전체 게시판</a>
                <li id="a2">의료IT공학과</li>
                <li id="a3">간호학과</li>
                <li id="a4">의공학과</li>
                <li id="a4">안녕</li>
                <li id="a4">안녕</li>
            </ul>

            <ul class="notice">
                <span><i class="fas fa-exclamation-triangle"></i>공지사항</span>
                <li id="n2">수강신청</li>
                <li id="n3">등록금 납부</li>
            </ul>

            <ul class="topProject">
                <span><i class="fas fa-fire"></i>인기 프로젝트</span>
                <li id="hp1">의료IT 프로젝트</li>
                <li id="hp2">의료IT 프로젝트</li>
                <li id="hp3">의료IT 프로젝트</li>
            </ul>

            <ul class="question">
                <a href="{% url 'boardApp:question-and-answer' %}"><i class="fas fa-question-circle"></i>문의사항</a>
                <li id="q2">문의사항 게시판</li>
            </ul>
        </ul>
    </section>

    <!-- Floating Button -->
    <button class="btn_chat">
        <i class="far fa-comments"></i>
    </button>

    <div class="chatArea">
        <div class="infoArea">
            <span class="chat-room-name">의료IT공학과 채팅방</span>
            <button class="chatClose"><i class="fas fa-times"></i></button>
        </div>
        <div class="chat-contents"></div>
        <div class="inputArea">
            <input class="input-txt" type="text">
            <button class="enter-btn"><i class="fas fa-paper-plane"></i></button>
        </div>
    </div>

    <script src="{% static 'js/mainpage.js' %}"></script>
    <script src="{% static 'js/boardPageAjax.js' %}"></script>
    <script src="{% static 'js/boardpage.js' %}"></script>
</body>

</html>

boardApp/templates/question.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 ,minimum-scale=1.0,maximum-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/mainpage.css' %}">
    <link rel="stylesheet" href="{% static 'css/boardpage.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap" rel="stylesheet">
    <script
      src="https://kit.fontawesome.com/bc1f5db172.js"
      crossorigin="anonymous"
    ></script>
    <title>Konstargram</title>
</head>
<body>
    <header>
        <div class="header-left">
            <a href="{% url 'mainApp:mainPage' %}"><img src="" alt="">로고</a>
            <i class="fas fa-chevron-right"></i>
            <a href="{% url 'boardApp:question-and-answer' %}">문의사항</a>
        </div>
        <div class="header-right">
            <div class="realtimeSearch">
                <span class="realtimeSearch-span">
                    실시간 인기 검색어
                    <i class="fas fa-caret-down"></i>
                </span>
                <div class="realtimeSearch-dropdown">
                    <a href="#" id="s1">삼색이</a>
                    <a href="#" id="s2">야통이</a>
                    <a href="#" id="s3">무</a>
                </div>
            </div>
            <input type="text" placeholder="검색" id="search">
            <a href="{% url 'loginSigninApp:login' %}" id="login">로그인</a>
            <i class="fas fa-user"></i>
            <i class="fas fa-bars" id="rightMenu"></i>
        </div>
    </header>

    <section class="chart">
        <!-- 문의사항 게시판 -->
        <div class="QAChart">
            <div class="board">
                <p class="board-txt">문의사항 게시판</p>
            </div>
            <ul class="postChart">
                <li>
                    <div>
                        <p class="Qcount">4</p>
                        <p class="postTitle">질문 있습니다~!</p>
                        <p>new</p>
                    </div>
                    <div>
                        <p class="writeTime">2021.02.24</p>
                        <p class="postCount">답변 2</p>
                    </div>
                </li>
                <li>
                    <div>
                        <p class="Qcount">3</p>
                        <p class="postTitle">문의사항 있습니다~!</p>
                        <p>new</p>
                    </div>
                    <div>
                        <p class="writeTime">2021.02.23</p>
                        <p class="postCount">답변 1</p>
                    </div>
                </li>
                <li>
                    <div>
                        <p class="Qcount">2</p>
                        <p class="postTitle">심심해요!</p>
                        <p></p>
                    </div>
                    <div>
                        <p class="writeTime">2021.02.22</p>
                        <p class="postCount">답변 0</p>
                    </div>
                </li>
                <li>
                    <div>
                        <p class="Qcount">1</p>
                        <p class="postTitle">불편해요!</p>
                        <p></p>
                    </div>
                    <div>
                        <p class="writeTime">2021.02.21</p>
                        <p class="postCount">답변 1</p>                            
                    </div>
                </li>
            </ul>
            <div class="Q-write">글쓰기</div>
            <div class="pageNum">
                <p class="prev">&#60</p>
                <p class="num">1</p>
                <p class="num">2</p>
                <p class="num selectedNum">3</p>
                <p class="next">&#62</p>
            </div>
        </div>

        <!-- 문의사항 게시글 -->
        <div class="questionPost">
            <div class="Qpost-title">
                <p class="Qtitle">문의사항 제목</p>
                <p class="Qtime">작성일</p>
            </div>
            <p class="Qpost-content">
                궁금한 점이 있습니다.<br>
                질문 있어요.<br>
                문의사항 있어요.<br><br>
                내일 정말 개강인가요???ㅜㅜ
            </p>
            <div class="Qlist">목록</div>
            <div class="answerPost">
                <p class="Atitle">A. 운영자의 답변<br></p>
                <p class="Acontent">
                    안타깝게도 사실로 밝혀졌습니다 :(<br>
                    문의해주셔서 감사합니다.
                </p>
            </div>
        </div>

        <!-- 문의사항 작성 -->
        <div class="writePost">
            <p id="Q-postform">문의사항 작성</p>
            <form class="Qpostform">
                <div class="title">
                    <p class="title-txt">제목</p>
                    <input type="text" id="titleId" placeholder="*제목을 입력해 주세요.">
                </div>
                <div class="content">
                    <p class="content-txt">내용</p>
                    <textarea name="contentName" id="contentId" cols="30" rows="10" placeholder="*내용을 입력해 주세요."></textarea>
                </div>
                <div class="password">
                    <p class="password-txt">암호</p>
                    <input type="text" id="passwordId" placeholder="비공개를 원하시면 암호를 입력해 주세요.">
                </div>
                <div>
                    <div id="essential">*는 필수 입력 사항</div>
                    <input id="write" type="button" value="작성">
                </div>
            </form>
        </div>
        <!-- Right Chart -->
        <ul class="rightChart">
            <ul class="noticeBoard">
                <a href="{% url 'boardApp:boardPage' %}"><i class="fas fa-clipboard"></i>전체 게시판</a>
                <li id="a2">의료IT공학과</li>
                <li id="a3">간호학과</li>
                <li id="a4">의공학과</li>
                <li id="a4">안녕</li>
                <li id="a4">안녕</li>
            </ul>

            <ul class="notice">
                <span><i class="fas fa-exclamation-triangle"></i>공지사항</span>
                <li id="n2">수강신청</li>
                <li id="n3">등록금 납부</li>
            </ul>

            <ul class="topProject">
                <span><i class="fas fa-fire"></i>인기 프로젝트</span>
                <li id="hp1">의료IT 프로젝트</li>
                <li id="hp2">의료IT 프로젝트</li>
                <li id="hp3">의료IT 프로젝트</li>
            </ul>

            <ul class="question">
                <a href="{% url 'boardApp:question-and-answer' %}"><i class="fas fa-question-circle"></i>문의사항</a>
                <li id="q2">문의사항 게시판</li>
            </ul>
        </ul>
    </section>

    <!-- Floating Button -->
    <button class="btn_chat">
        <i class="far fa-comments"></i>
    </button>

    <div class="chatArea">
        <div class="infoArea">
            <span class="chat-room-name">의료IT공학과 채팅방</span>
            <button class="chatClose"><i class="fas fa-times"></i></button>
        </div>
        <div class="chat-contents"></div>
        <div class="inputArea">
            <input class="input-txt" type="text">
            <button class="enter-btn"><i class="fas fa-paper-plane"></i></button>
        </div>
    </div>

    <script src="{% static 'js/question.js' %}"></script>
</body>
</html>